### ISSUE TITLE
Falkonry C# Client version not incremented caused Data stream ingestion failure.

### ISSUE THREAD

**Issue by AshwinNBhanushali** [Falkonry/falkonry-csharp-client#44]
@dilpeshjain 
As discussed every time we are releasing the falkonry c# client we need to increment the Assemebly version.
If we do not increase the version then installer will not update the .dll files when users will upgrade Falkonry Agent from 1.1.15 --> 1.1.17.
Below is the attached screenshot just for reference. where you need to increment version.
![csharpclientversionint](https://user-images.githubusercontent.com/1049452/36728970-944aa358-1be8-11e8-9a39-722821290d4f.PNG)

**Comment by phagunbaya** [comment]
@AshwinNBhanushali Start using Nuget package for FalkonryClient.https://www.nuget.org/packages/FalkonryClient
